import {useEffect,useState} from 'react';
import {beirutNow,validateReservation} from '../lib/reservation';
import {restaurant,wa} from '../data/restaurant';
import {Arrow,DeliveryLink} from './muu-shell';
export function VisitContent(){
 const [date,setDate]=useState(''),[time,setTime]=useState('19:00'),[party,setParty]=useState('2'),[message,setMessage]=useState(''),[today,setToday]=useState(''),[error,setError]=useState('');
 useEffect(()=>{setToday(beirutNow().date)},[]);
 function prepare(e:React.FormEvent){e.preventDefault();const now=beirutNow();setToday(now.date);const problem=validateReservation(date,time,party,now);setError(problem);setMessage(problem?'':'Hello Muu! I would like to enquire about a table for '+party+' guests on '+date+' at '+time+' (Beirut time). Could you confirm availability? Thank you.');}
 return <><section className="visit-hero page-width"><span className="eyebrow">THE VILLAGE · DBAYEH</span><h1>Good company.<br/><em>Great place to meet.</em></h1><p>Lunch, dinner, or a table full of your favourite people.</p></section>
 <section className="contact-grid page-width"><div className="address-card"><span className="location-symbol" aria-hidden="true">⌖</span><h2>Find us<br/>at The Village.</h2><address>{restaurant.address}</address><p>{restaurant.mapsUrl ? 'Get directions to Muu at The Village, Dbayeh.' : 'For the exact arrival pin, ask the team on WhatsApp.'}</p><a className="solid-cta ivory" href={restaurant.mapsUrl ?? wa('Hello Muu! Could you send me your exact Google Maps location pin and arrival directions at The Village, Dbayeh?')} target="_blank" rel="noreferrer">{restaurant.mapsUrl ? 'Google Maps Directions' : 'Ask for Directions'} <Arrow/></a></div><div className="contact-info"><div><h2>Stay for a while.</h2><p>{restaurant.hours}</p><p className="muted">Lunch & dinner daily · Beirut time</p></div><div><h2>Say hello.</h2><a className="phone-large" href={restaurant.phoneHref}>{restaurant.telephone}</a><a className="ink-link" href={restaurant.whatsapp} target="_blank" rel="noreferrer">WhatsApp <Arrow/></a></div><div><h2>Bring your best friend.</h2><p>Muu’s official Instagram lists the restaurant as pet friendly. Contact the team about your visit.</p></div></div></section>
 <section className="reservation page-width" id="request-table"><div><span className="eyebrow">LET’S GET TOGETHER</span><h2>Your next Muu moment<br/><em>starts here.</em></h2><p>Send a table enquiry directly to the team.<br/>Your reservation is confirmed only when Muu replies.</p></div><form onSubmit={prepare} className="reservation-form"><h3>Request a Table</h3><div className="form-row"><label>Date<input type="date" value={date} min={today} required onChange={e=>{setDate(e.target.value);setMessage('');setError('')}}/></label><label>Time (Beirut)<input type="time" min="12:00" max="23:59" required value={time} onChange={e=>{setTime(e.target.value);setMessage('');setError('')}}/></label></div><label>Number of guests<input type="number" min="1" max="50" required value={party} onChange={e=>{setParty(e.target.value);setMessage('');setError('')}}/></label>{error&&<p role="alert" className="form-error">{error}</p>}<button className="solid-cta forest" type="submit">Prepare enquiry <Arrow/></button>{message&&<div className="enquiry-preview" role="status"><h4>Your enquiry</h4><p>{message}</p><a className="solid-cta forest" href={wa(message)} target="_blank" rel="noreferrer">Continue on WhatsApp <Arrow/></a><p className="price-note">Review and send in WhatsApp. Nothing has been sent yet.</p></div>}</form></section>
 <section className="faq page-width"><h2>A few things<br/><em>you might be wondering.</em></h2><div>
 <details><summary>How do I place an order?<span>+</span></summary><p>Muu’s official ordering channel is WhatsApp. Contact the team to confirm dishes, current prices, availability and fulfilment.</p><a href={restaurant.whatsapp} target="_blank" rel="noreferrer">Continue on WhatsApp ↗</a></details>
 <details><summary>Do you deliver?<span>+</span></summary><p>Please ask Muu about delivery or pickup availability, service areas, fees, timing and payment. These details are not confirmed on this preview.</p><DeliveryLink/></details>
 <details><summary>Can I book a table here?<span>+</span></summary><p>You can prepare a table enquiry above and send it on WhatsApp. This is an enquiry, not a confirmed booking.</p></details>
 <details><summary>What about allergies or dietary needs?<span>+</span></summary><p>Please tell the team about allergies or dietary requirements before ordering. Menu descriptions do not guarantee allergen safety.</p><a href={restaurant.phoneHref}>Call Muu ↗</a></details>
 <details><summary>What if I need help with access or parking?<span>+</span></summary><p>Contact the restaurant for current parking, step-free access and seating arrangements before your visit.</p></details>
 </div></section></>
}
