import {createFileRoute} from '@tanstack/react-router';
import {Shell,Arrow,VisitPanel,DeliveryLink} from '../components/muu-shell';
import {Hero} from '../components/muu-hero';
import {restaurant} from '../data/restaurant';
export const Route=createFileRoute('/')({component:Home});
function Home(){return <Shell><Hero/>
<section className="intro page-width"><span className="intro-mark" aria-hidden="true">m.</span><div><p className="intro-line">Good food.<br/>Your favourite people.<br/><em>That’s the Muu way.</em></p><p>From Australian entrecôte and smoked ribs to burgers, seafood and sharing platters. Find your flavour, then settle in.</p></div></section>
<section className="featured page-width"><div className="section-heading"><span className="eyebrow">A TASTE OF MUU</span><h2>Find your next<br/><em>“just one more bite.”</em></h2><a className="ink-link" href="/menu">Explore the menu <Arrow/></a></div>
<div className="featured-layout"><a className="dish-feature main-dish" href="/menu?dish=card12"><div className="photo-frame"><img src="/assets/hq/steak-1200.webp" srcSet="/assets/hq/steak-800.webp 800w, /assets/hq/steak-1200.webp 1200w, /assets/hq/steak.webp 2400w" sizes="(max-width: 700px) calc(100vw - 40px), (max-width: 1000px) 55vw, 660px" width="2400" height="1792" loading="lazy" alt="AI-enhanced Muu Entrecôte Australian with fries and vegetables"/></div><div className="dish-caption"><div><small>FEATURED · MAIN COURSE</small><h3>Entrecôte Australian <span>300g</span></h3></div><span className="dish-link" aria-hidden="true">↗</span></div></a>
<div className="side-dishes"><a className="dish-feature" href="/menu?dish=card2"><div className="photo-frame"><img src="/assets/hq/burger-1200.webp" srcSet="/assets/hq/burger-800.webp 800w, /assets/hq/burger-1200.webp 1200w, /assets/hq/burger.webp 2400w" sizes="(max-width: 700px) calc(100vw - 40px), 40vw" width="2400" height="1792" loading="lazy" alt="AI-enhanced Muu Angus Beef Burger with fries"/></div><div className="dish-caption"><h3>Angus Beef Burger</h3><span className="dish-link" aria-hidden="true">↗</span></div></a><a className="dish-feature" href="/menu?dish=card6"><div className="photo-frame"><img src="/assets/hq/dessert-1200.webp" srcSet="/assets/hq/dessert-800.webp 800w, /assets/hq/dessert-1200.webp 1200w, /assets/hq/dessert.webp 2400w" sizes="(max-width: 700px) calc(100vw - 40px), 40vw" width="2400" height="1792" loading="lazy" alt="AI-enhanced Muu Pan Perdu"/></div><div className="dish-caption"><h3>Muu Pan Perdu</h3><span className="dish-link" aria-hidden="true">↗</span></div></a></div></div></section>
<section className="sharing"><div className="sharing-inner page-width"><div className="sharing-image"><img src="/assets/hq/platter-1200.webp" srcSet="/assets/hq/platter-800.webp 800w, /assets/hq/platter-1200.webp 1200w, /assets/hq/platter.webp 2400w" sizes="(max-width: 700px) calc(100vw - 40px), 40vw" width="2400" height="1792" loading="lazy" alt="AI-enhanced Muu Smoked Assorted Platter"/></div><div className="sharing-copy"><h2>Pass the plates.<br/><em>Stay a little longer.</em></h2><p>The Muu Smoked Assorted Platter brings pulled pork, beef, sausages, chicken and salmon to the table. Made for four, ready to share.</p><a className="outline-cta" href="/menu?dish=card17">See the platter <Arrow/></a></div></div></section>
<section className="order-strip page-width"><p>Craving Muu at home?</p><div><p>Talk to the team about availability and delivery.</p><DeliveryLink/></div></section>
<VisitPanel/>
<section className="instagram-strip page-width"><span>For a little more Muu.</span><a href={restaurant.instagram} target="_blank" rel="noreferrer">@muugrillhouse <Arrow/></a></section>
</Shell>}
